CREATE TABLE roles (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	role NVARCHAR(50) NOT NULL
) AUTO_INCREMENT = 1000;

CREATE  TABLE users (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    username NVARCHAR(100) NOT NULL,
    password CHAR(64) NOT NULL,
    email NVARCHAR(150),
    phone INT,
    role_ID INT NOT NULL DEFAULT 1000,
    FOREIGN KEY (role_ID) REFERENCES roles(ID)
) AUTO_INCREMENT = 1000;

